let models=[];
const group=document.querySelector('#modelGroup'),side=document.querySelector('#side'),type=document.querySelector('#type'),fence=document.querySelector('#fence'),sideField=document.querySelector('#sideField'),typeField=document.querySelector('#typeField'),fenceField=document.querySelector('#fenceField'),catalog=document.querySelector('#catalog'),title=document.querySelector('#resultTitle'),count=document.querySelector('#resultCount'),clear=document.querySelector('#clearFilters');
let observer;
function reset(){side.value='';type.value='';fence.value=''}
function update(){sideField.hidden=true;typeField.hidden=true;fenceField.hidden=true;if(group.value==='esteira-90'){sideField.hidden=false;if(side.value)typeField.hidden=false;if(side.value&&type.value)fenceField.hidden=false}if(group.value==='esteira-reta'){typeField.hidden=false;if(type.value)fenceField.hidden=false}render()}
function match(m){if(group.value==='todos')return true;if(m.group!==group.value)return false;if(group.value==='sem-esteiras')return true;if(group.value==='esteira-90')return m.side===side.value&&m.type===type.value&&m.fence===fence.value;if(group.value==='esteira-reta')return m.type===type.value&&m.fence===fence.value;return false}
function label(g){return {'sem-esteiras':'Sem esteiras','esteira-90':'Esteira 90º','esteira-reta':'Esteira reta'}[g]||g}
function card(m){let p=m.available?`<div class="lazy-model" data-src="modelos/${m.file}"><div class="preview-loading"><span class="spinner"></span><small>Carregando prévia</small></div></div>`:`<div class="placeholder">3D</div>`;return `<article class="card"><div class="visual"><span class="number">${m.number}</span>${p}${m.available?'':'<span class="soon">Em breve</span>'}</div><div class="body"><span class="pill">${label(m.group)}</span><h3>${m.name}</h3>${m.available?`<a class="primary" href="visualizador.html?modelo=${encodeURIComponent(m.id)}">Visualizar modelo</a>`:'<button class="disabled" disabled>Modelo ainda não disponível</button>'}</div></article>`}
function lazy(){if(observer)observer.disconnect();observer=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;let h=e.target,v=document.createElement('model-viewer');v.className='card-model';v.src=h.dataset.src;v.setAttribute('camera-controls','');v.setAttribute('auto-rotate','');v.setAttribute('rotation-per-second','8deg');v.setAttribute('interaction-prompt','none');v.setAttribute('shadow-intensity','.8');v.setAttribute('disable-zoom','');v.addEventListener('load',()=>h.classList.add('loaded'));h.appendChild(v);observer.unobserve(h)}),{rootMargin:'120px 0px'});document.querySelectorAll('.lazy-model').forEach(x=>observer.observe(x))}
function render(){if(!group.value){title.textContent='Selecione uma categoria';count.textContent='';catalog.innerHTML='<div class="empty">Escolha o modelo de visualização para começar.</div>';return}if((group.value==='esteira-90'&&(!side.value||!type.value||!fence.value))||(group.value==='esteira-reta'&&(!type.value||!fence.value))){title.textContent='Complete as opções';count.textContent='';catalog.innerHTML='<div class="empty">Preencha o próximo campo para continuar.</div>';return}let a=models.filter(match);title.textContent=group.value==='todos'?'Todos os modelos':group.value==='sem-esteiras'?'Modelos sem esteira':a.length===1?'Modelo encontrado':'Modelos encontrados';count.textContent=`${a.length} ${a.length===1?'modelo':'modelos'}`;catalog.innerHTML=a.map(card).join('');lazy()}
group.onchange=()=>{reset();update()};side.onchange=()=>{type.value='';fence.value='';update()};type.onchange=()=>{fence.value='';update()};fence.onchange=render;clear.onclick=()=>{group.value='';reset();update()};fetch('modelos.json').then(r=>r.json()).then(d=>{models=d;update()});